### ISSUE TITLE
Question: Are u Planning to improve the public blog view?

### ISSUE THREAD

**Issue by Naoray** [Laralum/Blog#6]
Are u Planning to improve the public blog view?

currently it looks a bit "simple" ;-)
![image](https://cloud.githubusercontent.com/assets/10154100/26005497/85a71988-3739-11e7-9b80-6f6664684687.png)

btw.: I am currently testing everything out and so far it looks like you two did a great job!! Keep up the good work

**Comment by ConsoleTVs** [comment]
Hello @Naoray , All the public views are very very very html simple. Why ? Because everybody can adapt the public views to their template. Remember you can edit them by publishing the views, then they will be available under:

```
resources/views/vendor/laralum_PACKAGE
```

Example, for the blog package, you can edit them after publishing them on:

```
resources/views/vendor/laralum_blog
```

If you have any suggestion tell us. The reason of the simple layout is just for easy-adaptation into your template, because everybody should understand plain HTML... :)

**Comment by 24aitor** [comment]
Well after reconsider your question, we've decided to maintain the same html simple but including a simple classless css framework that improves the style of public views :)

Here's the result:

![CSS Improvements](https://sc-cdn.scaleengine.net/i/b290a66719f7459b17d842ba993d01b1.png)
